# Generated by Django 6.0.3 on 2026-03-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_businesssettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssettings",
            name="currency",
            field=models.CharField(
                choices=[("USD", "Dollar ($)"), ("INR", "Rupee (₹)")],
                default="USD",
                max_length=5,
            ),
        ),
    ]
