# Generated by Django 6.0.3 on 2026-03-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_businesssettings_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyslip',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalised', 'Finalised'), ('paid', 'Paid')], default='draft', max_length=20),
        ),
    ]
