# Generated by Django 6.0.3 on 2026-04-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dutyslip_status_companycarrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='github_repo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='github_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
