# Generated by Django 6.0.4 on 2026-04-27 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_businesssettings_github_repo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='outstation_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='companycarrate',
            name='outstation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dutyslip',
            name='slip_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('outstation', 'Outstation')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='dutyslipentry',
            name='entry_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('outstation', 'Outstation')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='dutyslipentry',
            name='outstation_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dutyslip',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalised', 'Finalised'), ('paid', 'Paid')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='dutyslipentry',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dutyslipentry',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DutySlipEntryOutStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_kms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_kms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_kms', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_kms', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_kms_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('extra_hrs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_hrs_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('driver_bhatta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parking', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('row_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.car')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='out_station_entries', to='api.company')),
                ('duty_slip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='out_station_entries', to='api.dutyslip')),
            ],
        ),
    ]
