# Generated by Django 6.0.3 on 2026-06-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_dutyslip_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesssettings",
            name="logo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
