# Generated by Django 6.0.3 on 2026-06-08 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_rename_terminology"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dutyslip",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trips",
                to="api.company",
            ),
        ),
        migrations.AlterField(
            model_name="dutyslip",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trips",
                to="api.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="api.company",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="party_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="api.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="api.party",
            ),
        ),
        migrations.DeleteModel(
            name="DutySlipEntryOutStation",
        ),
    ]
