repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff
        args: [--fix]
        files: ^backend/

      - id: ruff-format
        files: ^backend/

  - repo: local
    hooks:
      - id: frontend-lint
        name: frontend-lint
        entry: bash -c 'cd frontend && npm run lint'
        language: system
        pass_filenames: false
        files: ^frontend/

      - id: electron-lint
        name: electron-lint
        entry: bash -c 'cd electron && npm run lint'
        language: system
        pass_filenames: false
        files: ^electron/